//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulta
    {
        public int Id { get; set; }
        public int Nro_Med { get; set; }
        public int Nro_Especialidad { get; set; }
        public System.DateTime FechaHora { get; set; }
        public int Id_Consultorio { get; set; }
        public int Nro_Consultorio { get; set; }
        public Nullable<bool> Activa { get; set; }
    
        public virtual Consultorio Consultorio { get; set; }
        public virtual Especialidad Especialidad { get; set; }
        public virtual Medico Medico { get; set; }
    }
}
