//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public int Cedula { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Sexo { get; set; }
        public System.DateTime Fecha_Nacimiento { get; set; }
        public string Mail { get; set; }
        public Nullable<int> Telefono { get; set; }
        public Nullable<int> Celular { get; set; }
        public int EstadoCivil { get; set; }
        public string MedicoRef { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual Estado_Civil Estado_Civil { get; set; }
    }
}
