//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int Cedula { get; set; }
        public string Nick { get; set; }
        public string Pass { get; set; }
        public int Rol { get; set; }
        public bool Activo { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
